name: Test Custom Runner Image

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: Check Installed Tools
        run: |
          oc version --client
          helm version --client
          jq --version
          oc get pod
          